server.port: 8080

secret:
  key: "782F413F4428472B4B6250655368566D5971337436773979244226452948404D"
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/magnit-db
    username: postgres
    password:
    driver-class-name: org.postgresql.Driver
  main:
    allow-circular-references: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mvc:
    throw-exception-if-no-handler-found: true
    log-request-details: true
  flyway:
    baseline-on-migrate: true

logging:
  level:
    org.springframework.web: DEBUG
    com.hulk.magnit_phonenumber_database_service: DEBUG
    org.hibernate.sql: DEBUG
  file:
    path: "./log"
  logback:
    rolling policy:
      clean-history-on-start: true
