server.port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/magnit-db
    username: postgres
    password: qwe
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org.springframework.web: DEBUG
    com.hulk.magnit_phonenumber_database_service: DEBUG
    org.hibernate.sql: DEBUG
